spring:
  application:
    name: service-euerka-feign
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8902

feign:
  hystrix:
    enabled: true # 开启Feign熔断
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/