spring:
  application:
    name: service-euerka-feign

server:
  port: 8904

feign:
  hystrix:
    enabled: true # 开启Feign熔断
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/